### ISSUE TITLE
The first Meetup

### ISSUE THREAD

**Issue by somebody32** [BarcelonaJS/react#1]
Hey everyone!

Thanks for stopping by. In this issue, we're going to iron out all details about the first Barcelona React Meetup.

### What we have for now

Possible date: 29 of June, 19:00
Place: Redbooth Office, Vía Augusta 59

### Talks

We have 2 confirmed talks already

#### Intro to react-virtualized
by @edulan

React is an awesome library that allows us to render things ultra fast. But sometimes the amount of data to display is so big that it can make your browser freeze or even to crash. For those scenarios, virtual rendering is a really useful technique that can help us as it only renders visible stuff on the screen.

In this talk, I'll talk about virtual rendering in React and how react-virtualized library allows us to use it effectively. We'll see real examples, how it works and some implementation considerations when using it.

#### Unit Testing in React + Redux Applications 
by @dmitry-zaets

Why should you test your app? How to start? Which Redux parts and React components should you test and why? Which testing toolset and approach to choose? I will try to give an answer to all these questions in my talk.

**Comment by Gpx** [comment]
Hey @somebody32 the plan looks great.

Our idea was to have a workshop where we code a simple app just to give people a taste of React. We wanted to create a simple Pokédex that communicates with an external API.

Since you guys are way ahead of us I'd say we should change our plans and help you out. Do you think it would be beneficial to include such a workshop during the meetup, or maybe we can have it as a separate event? Or do you see some other areas where we can help out?

**Comment by somebody32** [comment]
@Gpx great idea! Normally workshops are very long events, so I think that combine it together with the meetup could be hard on the workday (and I think will require a different place, where everyone can sit with their laptops). But it will be really cool if you have you date set before the meetup, so we can shout out about your workshop between the talks

**Comment by Gpx** [comment]
We were aiming for July, I don't know the date yet but I'll let you know.

I think it would also make sense to group both events under the same Meetup group, what do you think?

**Comment by somebody32** [comment]
Totally makes sense to me

**Comment by Gpx** [comment]
Ok, so I'll let you know the date. Meanwhile, if you need help with the first event I'm happy to help. And please send me the event link so I can join 😀

**Comment by somebody32** [comment]
and we're live http://www.meetup.com/ReactJS-Barcelona/events/231742290/

**Comment by Gpx** [comment]
I saw the notification only now and I'm in the waiting list 😞

**Comment by somebody32** [comment]
done/done 🎉
