### ISSUE TITLE
React Storybook

### ISSUE THREAD

**Issue by nickytonline** [BarcelonaJS/react#3]
Twitter: @nickytonline

I'd like to do a talk on [React Storybook] ( https://github.com/kadirahq/react-storybook).

**Comment by somebody32** [comment]
Great, @nickytonline! is 26th of July ok for you? We're planning the next meetup for that day.
And can you please shoot me an email with a short talk description? somebody32@gmail.com

**Comment by nickytonline** [comment]
Ilya,

The 26th works for me. I will shoot you an email with the description of
the talk.


Cheers,

Nick

**Comment by somebody32** [comment]
Hi, @nickytonline. Looks like I was too fast on the decision about 26th. Is 25th of July working for you too?

**Comment by nickytonline** [comment]
25th is fine as well and I will send you the description of the talk
tonight.

**Comment by nickytonline** [comment]
[React Storybook](https://github.com/kadirahq/react-storybook) provides a way to develop and design components rapidly in isolation (without your app).

The talk will cover:
* An overview or React Storybook
* Setting up React Storybook
* A demo of React Storybook in action
* Out of scope but to get mentions:
	* extending React Storybook
	* competing projects

**Comment by nickytonline** [comment]
The slides will be made available [here](https://github.com/nickytonline/bcn-reactjs-storybook-talk-2016-07-25)
