### ISSUE TITLE
CSS Modules

### ISSUE THREAD

**Issue by Gpx** [BarcelonaJS/react#4]
CSS improved a lot in the last years but for many it's still one of the hardest parts to handle while developing big web applications. Pre-processed languages like [Sass](http://sass-lang.com/) and [Less](http://lesscss.org/) added many new features but we still have to rely on methodologies such as [BEM](https://en.bem.info/methodology/) and [OOCSS](http://oocss.org/) to avoid name collisions.

In ReactJS many people tried to solve these issues using the `style` attribute or by developing libraries like [Radium](http://stack.formidable.com/radium/). Although these approaches fix some of the problems they bring new challenges on their own.

[CSS Modules](https://github.com/css-modules/css-modules) give you the best of both words. Write CSS code using all the tools you love and forget about name collisions.

In my talk I'll explain what CSS Modules are, why they are so good and how you can use them in your project.

**Comment by somebody32** [comment]
Thanks a lot, @Gpx, for the proposal! Is 26th of July ok for you?

**Comment by Gpx** [comment]
Yes, the 26th is fine.
